/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.panel;

import com.mycompany.controlador.Validaciones;
import com.mycompany.entidades.Usuario;
import static com.mycompany.panel.panelUsuarios.CUsuarios;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nandobot
 */
public class IngresoUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form IngresoUsuarios
     */
    
    String funcion;
    String CedG;
   
    
    public IngresoUsuarios(String fun) {
        initComponents();
        funcion = fun;
        if(funcion.equals("Editar")){
            title1.setText("EDITAR USUARIO");
        }
    }
    
    public void setDatos(Usuario e){
        CedG = e.getCedula();
        txtCedula.setText(e.getCedula());
        txtNombre.setText(e.getNombre());
        txtApellidoP.setText(e.getApellidoP());
        txtApellidoM.setText(e.getApellidoM());
        txtFacultad.setText(e.getFacultad());
        txtCarrera.setText(e.getCarrera());
        txtDomicilio.setText(e.getDomicilio());
        txtTelefono.setText(String.valueOf(e.getTelefono()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedula = new javax.swing.JTextField();
        apMLbl = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        domLbl = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        txtFacultad = new javax.swing.JTextField();
        apPLbl = new javax.swing.JLabel();
        apMLbl1 = new javax.swing.JLabel();
        nameLbl1 = new javax.swing.JLabel();
        txtApellidoM = new javax.swing.JTextField();
        phoneLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1350, 900));
        setPreferredSize(new java.awt.Dimension(1350, 900));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1350, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 920));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
        });
        jPanel1.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 501, 40));

        apMLbl.setText("Nombre");
        jPanel1.add(apMLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 321, -1));

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 501, 40));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 18, 450));

        domLbl.setText("Carrera");
        jPanel1.add(domLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 457, -1));

        txtCarrera.setToolTipText("");
        txtCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarreraKeyReleased(evt);
            }
        });
        jPanel1.add(txtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 518, 38));

        phoneLbl.setText("Domicilio");
        jPanel1.add(phoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 459, -1));

        nameLbl.setText("Facultad");
        jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 278, -1));

        txtDomicilio.setToolTipText("");
        txtDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDomicilioKeyReleased(evt);
            }
        });
        jPanel1.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 518, 40));

        txtFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFacultadActionPerformed(evt);
            }
        });
        txtFacultad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFacultadKeyReleased(evt);
            }
        });
        jPanel1.add(txtFacultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 501, 40));

        apPLbl.setText("Cedula");
        jPanel1.add(apPLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 319, -1));

        apMLbl1.setText("Segundo Apellido");
        jPanel1.add(apMLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 259, 33));

        nameLbl1.setText("Primer Apellido");
        jPanel1.add(nameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 357, -1));

        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyReleased(evt);
            }
        });
        jPanel1.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 501, 40));

        phoneLbl1.setText("Telefono");
        jPanel1.add(phoneLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 677, 24));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, 220, 80));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 220, 80));

        title1.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        title1.setText("REGISTRAR USUARIO");
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1326, 64));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, -1));

        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyReleased(evt);
            }
        });
        jPanel1.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 501, 40));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 520, 40));

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        if(Validaciones.esCedula(txtCedula))
            Validaciones.pinta_text(txtCedula);
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtNombre))
            Validaciones.pinta_text(txtNombre);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtApellidoP))
            Validaciones.pinta_text(txtApellidoP);
    }//GEN-LAST:event_txtApellidoPKeyReleased

    private void txtApellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtApellidoM))
            Validaciones.pinta_text(txtApellidoM);
    }//GEN-LAST:event_txtApellidoMKeyReleased

    private void txtFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFacultadActionPerformed

    private void txtFacultadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFacultadKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtFacultad))
            Validaciones.pinta_text(txtFacultad);
    }//GEN-LAST:event_txtFacultadKeyReleased

    private void txtCarreraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarreraKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtCarrera))
            Validaciones.pinta_text(txtCarrera);
    }//GEN-LAST:event_txtCarreraKeyReleased

    private void txtDomicilioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDomicilioKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esLetras(txtDomicilio))
            Validaciones.pinta_text(txtDomicilio);
    }//GEN-LAST:event_txtDomicilioKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        if(Validaciones.esTelefono(txtTelefono))
            Validaciones.pinta_text(txtTelefono);
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Validacion()){
            String ced= txtCedula.getText();
            String nombre = txtNombre.getText();
            String apellidop = txtApellidoP.getText();
            String apellidom = txtApellidoM.getText();
            String facultad = txtFacultad.getText();
            String carrera = txtCarrera.getText();
            String domicilio = txtDomicilio.getText();
            String telefono = txtTelefono.getText();
            
            Usuario e = new Usuario(ced, nombre, apellidop, apellidom, domicilio, telefono, carrera, facultad);
            
            if(funcion.equals("Ingresar")){
                try{
                    CUsuarios.Agregar(e); 
                }catch(SQLException ex){
                    
                }
            }else{
                try{
                    CUsuarios.Editar(e, CedG);  
                }catch(SQLException ex){
                    
                }
                this.hide();
            }
            panelUsuarios.Listar();

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private boolean Validacion(){
        System.out.println(funcion);
        String msj = "Los siguientes campos tienen errores: ";
        boolean ok = true;
        
        if(!Validaciones.esCedula(txtCedula)){
            msj += "Cedula, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtNombre)){
            msj += "Nombre, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtApellidoP)){
            msj += "Apellido paterno, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtApellidoM)){
            msj += "Apellido materno, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtFacultad)){
            msj += "Facultad, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtCarrera)){
            msj += "Carrera, ";
            ok = false;
        }
        
        if(!Validaciones.esLetras(txtDomicilio)){
            msj += "Domicilio, ";
            ok = false;
        }
        
        if(!Validaciones.esTelefono(txtTelefono)){
            msj += "Telefono, ";
            ok = false;
        }
        
        Usuario lb = null;
        try{
            lb = CUsuarios.getUsuario(txtCedula.getText());
        }catch(SQLException ex){
                    
        }
        
        if(lb!=null){
            if(funcion.equals("Ingresar")){
                JOptionPane.showMessageDialog(null, "Ya existe un usuario con la cedula: "+txtCedula.getText());
                ok = false;
            }
            
        }
        
        if(ok){
            if(funcion.equals("Ingresar")){
                msj = "Usuario guardado correctamente";
            }else{
                msj = "Usuario editado correctamente";
            }
        }
        
        JOptionPane.showMessageDialog(null, msj);
        return ok;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apMLbl;
    private javax.swing.JLabel apMLbl1;
    private javax.swing.JLabel apPLbl;
    private javax.swing.JLabel domLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneLbl1;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCarrera;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtFacultad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
