/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.panel;

import com.mycompany.controlador.TListaLibros;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nandobot
 */
public class Libros extends javax.swing.JPanel {

    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
        this.CLibros = new TListaLibros();
        panelFondo.add(new IngresoLibros("Ingreso"), "Ingreso");
        Listar();
    }
    
    static TListaLibros CLibros;
    
    public static void Listar(){
        try{
            tabla.setModel(CLibros.TablaBusquedaID("", "Completa"));
        }catch(SQLException ex){
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtdato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1350, 900));
        setPreferredSize(new java.awt.Dimension(1350, 900));
        setLayout(new java.awt.BorderLayout());

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo.setMinimumSize(new java.awt.Dimension(1350, 900));
        panelFondo.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1083, 13, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, -1, 48));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, 150, 70));

        txtdato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdatoKeyReleased(evt);
            }
        });
        jPanel1.add(txtdato, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 304, 48));

        tabla.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Fecha de Pub.", "Autor", "Categoría", "Edición", "Idioma", "Páginas", "Descripción", "Stock", "Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 124, 1232, 521));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BORRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 700, 150, 70));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 700, 150, 70));

        title1.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        title1.setText("Libros");
        jPanel1.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 259, 64));

        panelFondo.add(jPanel1, "card2");

        add(panelFondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelFondo.getLayout());
            cl.show(panelFondo, "Ingreso");
        }catch(Exception ex){System.out.println(ex.getMessage());}
        panelFondo.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            DefaultTableModel tablal = CLibros.TablaBusquedaID(txtdato.getText(), "Completa");
            if(tablal.getRowCount()<1){
                tablal = CLibros.TablaBusquedaVarios(txtdato.getText(), "Completa");
            }
            tabla.setModel(tablal);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtdatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyReleased
        if(txtdato.getText().equals("")){
            Listar();
        }
    }//GEN-LAST:event_txtdatoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(tabla.getSelectedRow()>=0){
            
            IngresoLibros IL = new IngresoLibros("Editar");
            panelFondo.add(IL, "Editar");
            try{
                CardLayout cl = (CardLayout)(panelFondo.getLayout());
                cl.show(panelFondo, "Editar");
            }catch(Exception ex){System.out.println(ex.getMessage());}
            panelFondo.repaint();
            
            String ced = tabla.getValueAt(tabla.getSelectedRow(), 1).toString();
            try{
                IL.setDatos(CLibros.getLibro(ced));
            }catch(SQLException ex){
                
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Escoja el libro a editar!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tabla.getSelectedRow()>=0){
            int opc = JOptionPane.showConfirmDialog(null, "Eliminar libro", "¿Esta seguro que desea eliminar este libro?\nTitulo:"
                    +tabla.getValueAt(tabla.getSelectedRow(), 2), 
                    JOptionPane.YES_NO_OPTION);
            if(opc == JOptionPane.YES_OPTION){
                String ced = tabla.getValueAt(tabla.getSelectedRow(), 1).toString();
                try{
                    CLibros.Eliminar(ced);
                }catch(Exception ex){}}
            
                Listar();
                
        }else{
            JOptionPane.showMessageDialog(null, "Escoja el libro a eliminar!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelFondo;
    private static javax.swing.JTable tabla;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtdato;
    // End of variables declaration//GEN-END:variables
}
