/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.panel;

import com.mycompany.controlador.TListaUsuario;
import java.awt.CardLayout;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nandobot
 */
public class panelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form Usuarios
     */
    public panelUsuarios() {
        initComponents();
        panelFondo.add(new IngresoUsuarios("Ingresar"), "Usuarios");
        jTable1.setModel(TListaUsuario.TablaPanelUsuario(TListaUsuario.lista));
    }
    
    public static void Listar(){
        jTable1.setModel(TListaUsuario.TablaPanelUsuario(TListaUsuario.lista));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        title1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1350, 900));
        setPreferredSize(new java.awt.Dimension(1350, 900));
        setLayout(new java.awt.BorderLayout());

        panelFondo.setMinimumSize(new java.awt.Dimension(1350, 900));
        panelFondo.setLayout(new java.awt.CardLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(1350, 900));
        bg.setPreferredSize(new java.awt.Dimension(1350, 900));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cedula", "Nombre", "Apellido P.", "Apellido M.", "Domicilio", "Teléfono", "Carrera"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 107, 1250, 520));
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, -1, 130));

        txtDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatoActionPerformed(evt);
            }
        });
        txtDato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatoKeyReleased(evt);
            }
        });
        bg.add(txtDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 304, 48));

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        bg.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 30, -1, 48));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("NUEVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 690, 150, 76));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bg.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 690, 150, 76));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BORRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        bg.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 690, 150, 76));

        title1.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        title1.setText("Usuarios");
        bg.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 30, -1, -1));

        panelFondo.add(bg, "card2");

        add(panelFondo, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            CardLayout cl = (CardLayout)(panelFondo.getLayout());
            cl.show(panelFondo, "Usuarios");
        }catch(Exception ex){System.out.println(ex.getMessage());}
        panelFondo.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            DefaultTableModel tabla = TListaUsuario.TablaBusquedaCed(txtDato.getText(), "Completa");
            if(tabla.getRowCount()<1){
                tabla = TListaUsuario.TablaBusquedaVarios(txtDato.getText(), "Completa");
            }
            jTable1.setModel(tabla);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatoActionPerformed

    private void txtDatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatoKeyReleased
        if(txtDato.equals("")){
            jTable1.setModel(TListaUsuario.TablaPanelUsuario(TListaUsuario.lista));
        }
    }//GEN-LAST:event_txtDatoKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTable1.getSelectedRow()>=0){
            int opc = JOptionPane.showConfirmDialog(null, "Eliminar usuario", "¿Esta seguro que desea eliminar este usuario?\nCedula:"
                    +jTable1.getValueAt(jTable1.getSelectedRow(), 2), 
                    JOptionPane.YES_NO_OPTION);
            if(opc == JOptionPane.YES_OPTION){
                String ced = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
                TListaUsuario.Eliminar(TListaUsuario.Buscar(ced));
                jTable1.setModel(TListaUsuario.TablaPanelUsuario(TListaUsuario.lista));
                try{
                    TListaUsuario.guardar();
                }catch(Exception ex){}
            }
        }else{
            JOptionPane.showMessageDialog(null, "Escoja el usuario a eliminar!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTable1.getSelectedRow()>=0){
            
            IngresoUsuarios IL = new IngresoUsuarios("Editar");
            panelFondo.add(IL, "Editar");
            try{
                CardLayout cl = (CardLayout)(panelFondo.getLayout());
                cl.show(panelFondo, "Editar");
            }catch(Exception ex){System.out.println(ex.getMessage());}
            panelFondo.repaint();
            
            String ced = jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString();
            IL.setDatos(TListaUsuario.getUsuario(TListaUsuario.Buscar(ced)));
        }else{
            JOptionPane.showMessageDialog(null, "Escoja el usuario a editar!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
